### ISSUE TITLE
AltGr + q does not insert /

### ISSUE THREAD

**Issue by malbarbo** [racket/drracket#393]
Using Windows 10 and pressing AltGr + q inserts / in any application, except in DrRacket where it triggers undo.

On Linux AltGr + q works fine on DrRacket and inserts /.

Here is the output of running  https://github.com/racket/gui/blob/master/gui-test/tests/gracket/showkey.rkt on Windows 10 and pressing AltGr+q

```
1 KEY: control
  rel-code: press
  other-codes: (#f #f #f #f)
  mods: CTL
2 KEY: menu
  rel-code: press
  other-codes: (#f #f #f #f)
  mods: META CTL = ALTGR
3 KEY: "/" = ASCII 47
  rel-code: press
  other-codes: (#f "q" = ASCII 113 "Q" = ASCII 81 #f)
  mods: META CTL = ALTGR
4 KEY: release
  rel-code: "q" = ASCII 113
  other-codes: ("Q" = ASCII 81 "/" = ASCII 47 #f #f)
  mods: META CTL = ALTGR
5 KEY: release
  rel-code: menu
  other-codes: (#f #f #f #f)
  mods:
```
