### ISSUE TITLE
Current keyboard layout (language) shouldn't affect keybindings

### ISSUE THREAD

**Issue by RuRo** [racket/drracket#467]
As the title says, hotkeys should work the same, no matter, what keyboard layout is selected. For example, if I have the `en-US` layout enabled, pressing `Ctrl+V` pastes the clipboard contents. But if I switch to some other layout, like `ru-RU` which doesn't have the same letter, where the `V` key is physically located on the keyboard and press the same physical key combination, the Russian letter 'м' is inserted instead of the clipboard contents.

```
DrRacket: v7.9
OS: Manjaro Linux (basically Arch Linux)
DE: KDE Plasma 5.20.5
```
If you need any extra info, feel free to ask.

**Comment by Metaxal** [comment]
What if the layout does have the same letter at a different place?

For example, I often use a variant of the French layout on a UK keyboard, and I expect Ctrl-V to paste, where V is the letter I press to print V (which is different from where the V is placed on my keyboard).

**Comment by RuRo** [comment]
> where V is the letter I press to print V (which is different from where the V is placed on my keyboard)

@Metaxal I don't really understand, what are you trying to say here.

---

Just to be clear, my issue is not about Physical keyboard layouts (QWERTY vs QWERTZ vs AZERTY), but about Virtual/Language layouts (en-US vs ru-RU). Here is a more concrete example.

The standard Russian physical keyboard looks something like this:
![keyboard](https://user-images.githubusercontent.com/3747318/110934634-4e041200-833f-11eb-9279-936798f61804.jpg)

Both the red and black letters are actually physically printed on the key caps. The user is then able to switch between the languages by pressing some key combination (commonly Alt+Shift). The currently selected language is shown as a small icon in the task bar.

I can type "Hello", if I have the en-US layout selected, but if I press the same physical keys while the ru-RU layout is selected, I will type "Руддщ" instead.

As you can see, there is no red (Cyrillic) letter V and the key which has the black (Latin) letter V has the Cyrillic letter М. The correct behaviour is for shortcuts to perform exactly the same action, ignoring which Virtual/Language layout is currently selected and only considering which physical key is pressed. This is how hotkeys already work in 99.999% of applications in both Windows and Linux, but for some reason it doesn't work in DrRacket on Linux.

**Comment by rfindler** [comment]
This is probably something going wrong at the `racket/gui` layer as that's what's taking the os-provided keyboard input and turning it into callbacks that DrRacket sees. 

@RuRo What happens if you run `racket -l tests/gracket/showkey` and try some of the non-working keystrokes? (Depending on how you've installed racket you may need to run `raco pkg install gui-test` first, so try that if you get an error that starts with `standard-module-name-resolver: collection not found for module path: (lib "tests/gracket/showkey")`.

**Comment by RuRo** [comment]
Pressing <kbd>Ctrl+C</kbd> in `racket -l tests/gracket/showkey`:
<details>
<summary>In en-US layout (works)</summary>

```
1 KEY: control
  rel-code: press
  other-codes: (control control control control)
  mods:
2 KEY: "c" = ASCII 99
  rel-code: press
  other-codes: ("C" = ASCII 67 #f #f "C" = ASCII 67)
  mods: CTL
3 KEY: release
  rel-code: "c" = ASCII 99
  other-codes: ("C" = ASCII 67 #f #f "C" = ASCII 67)
  mods: CTL
4 KEY: release
  rel-code: control
  other-codes: (control #f #f control)
  mods: CTL
```
</details>
<details>
<summary>In ru-RU layout (doesn't work)</summary>


```
1 KEY: control
  rel-code: press
  other-codes: (control control control control)
  mods:
2 KEY: "с" = ASCII 1089
  rel-code: press
  other-codes: ("С" = ASCII 1057 #f #f "С" = ASCII 1057)
  mods: CTL
3 KEY: release
  rel-code: "с" = ASCII 1089
  other-codes: ("С" = ASCII 1057 #f #f "С" = ASCII 1057)
  mods: CTL
4 KEY: release
  rel-code: control
  other-codes: (control #f #f control)
  mods: CTL
```
</details>
